CAP_NONE  = 0
CAP_VIDEO = 1
CAP_AUDIO = 2
CAP_OSD   = 3
CAP_DVD = 4
CAP_DVD_MENUS = 5
CAP_DYNAMIC_FILTERS = 6
CAP_VARIABLE_SPEED = 7
CAP_VISUALIZATION = 8
CAP_DEINTERLACE = 9
CAP_CANVAS = 10

STATE_NOT_RUNNING = 0
STATE_IDLE = 1
STATE_OPENING = 2
STATE_PLAYING = 3
STATE_PAUSED = 4

