#!/usr/bin/python
# -*- coding: iso-8859-1 -*-

import sys
import logging

logging.getLogger('epg').setLevel(logging.INFO)
import kaa
import kaa.epg

kaa.epg.load('test.db')
kaa.epg.update.config.load('test.cfg')
kaa.epg.update.config.save('test.cfg')
kaa.epg.update().connect(sys.exit, 0).ignore_caller_args = True
kaa.main.run()
